name: auto build HMCLPE - Android CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'main'
    # 在push tag时触发
    tags:
      - '*'
  pull_request:
    branches: [ main,master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup timezone
      # You may pin to the exact commit or the version.
      # uses: zcong1993/setup-timezone@7215c3ec086d387e4618c4b81482d06d998c90a9
      uses: zcong1993/setup-timezone@v1.1.2
      with:
        # which timezone you want to use
        timezone: Asia/Shanghai # default is UTC
    - name: Fuck you bad packet header
      run: |
        git config --global pack.windowMemory "100m"
        git config --global pack.packSizeLimit "100m"
        git config --global pack.threads "1"
        git config --global pack.deltaCacheSize "512m"
    - name: Checkout
      uses: actions/checkout@v2
    - name: fuck at JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Python
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: python3.8 -m pip install lanzou-api requests demjson setuptools==57.5.0
    - name: Fuck execute permission for gradlew
      run: chmod +x gradlew
    - name: Build♂with♂Gradle
      run: cd HMCLPE&&../gradlew build
    #step：上传apk 到action，在右上角查看
    # 官方文档 https://help.github.com/cn/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts#uploading-build-and-test-artifactst
    - name: Fuck↑ APK to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: HMCLPE-release-selfsigned.apk
        path: HMCLPE/build/outputs/apk/release/HMCLPE-release.apk
        asset_content_type: application/apk
    - name: Upload and share APK to lanzoucloud
      run: python UploadLZY.py '${{ secrets.lanzou_cookie }}'
    - name: Upload APK to Pgyer
      uses: JantHsueh/upload-file-action@master
      with:
        url: https://www.pgyer.com/apiv2/app/upload
        method: POST
        # ${{ secrets.pgyer_api_key }} 使用秘钥，如何设置下面会介绍
        forms: '{"_api_key":"${{ secrets.pgyer_api_key }}","buildInstallType":1}'
        fileForms: '{"file":"HMCLPE/build/outputs/apk/release/HMCLPE-release.apk"}'
